language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - sudo pip2 install supervisor
    - pip install -r dev_requirements.txt
script:
    - .githooks/pre-commit -f
    - python -m unittest discover
deploy:
    provider: pypi
    user: ixa
    password:
        secure: "i/CUjDVtSLg74kuLlKCAMAxOrj6WkxZpsXZG4Cz+30S5LXVqhgRfm3Ac0OY4LwMepksTNAqUUcV81p2Vf05y+1fp9q2d6g1C5gG+80pAaO7rDlRA6ce1tRjQmT4YrPDp9V5ngY5R1Y9ZmKuRKP6XYMJb5tzVfPE+JxyXneC9Ez8="
    server: https://pypi.python.org/pypi
    on:
        branch: release
        python: 3.4
