language: python
python:
    - "2.7"
install:
    - pip install -r dev_requirements.txt
script:
    - .githooks/pre-commit -f
    - python -m unittest discover
deploy:
    provider: pypi
    user: ixa
    password:
        secure: KotqwXcFnooWKlSp1jM98898loE9ugWpba7tXGcDFuHhXQGT/wXtNgzROa2EhPxs7IYfQtxq4HD3dadYSziuUzHRTTjg5YUiW9Gx4N0gFtfthraroKu4IB62B9k84YPmxIIZZNvkJOSd1Ip5x2/+TJntPcroi0UK4GFRhLmcOKM=
    server: https://pypi.python.org/pypi
    on:
        branch: release
        python: 2.7
